services:
  bomberman:
    image: sunderia/bomberman:1.0.0
    restart: unless-stopped
    # environment:
      # VELOCITY_SECRET: YLIyDwyeyxdQTDGz0Guyp971AYVnN7yu # if omitted, the server will disable velocity support
    ports:
      - "25565:25565"
